### ISSUE TITLE
Defining a project dependency for a specific Scala version

### ISSUE THREAD

**Issue by bmuschko** [prokod/gradle-crossbuild-scala#101]
Say I work on the multi-project build with two subprojects: `a` and `b`. `a` applies the `com.github.prokod.gradle-crossbuild` plugin and builds the code for the Scala versions 2.11 and 2.12. The project `b` uses code from project `a`, therefore defines a [project dependency](https://docs.gradle.org/current/userguide/declaring_dependencies_between_subprojects.html). Is there a way to express right now that the project should be depend on the artifact of `a` built with just Scala version 2.11 or 2.12 and its transitive closure of dependencies? Here's a [sample project](https://github.com/bmuschko/scala-multi-version) with the setup I described.

I guess the following could work but it's [poor practice](https://docs.gradle.org/current/userguide/cross_project_publications.html). Here, I am depending on the artifact directly.

_b/build.gradle:_

```
dependencies {
    crossBuildScala_211Implementation project.files(project(':a').tasks.crossBuildScala_211Jar.archiveFile.getAsFile())
    crossBuildScala_212Implementation project.files(project(':a').tasks.crossBuildScala_212Jar.archiveFile.getAsFile())
}
```

The [proper way](https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:simple-sharing-artifacts-between-projects) would be to define an "outgoing" artifact and add that to a consumable configuration. Am I just missing which configuration that is? The workaround could be to define this myself in project `a` and then reference it in project `b` but this logic should really live in the plugin.

_a/build.gradle:_

```
configurations {
    consumable211Jar {
        canBeConsumed = true
        canBeResolved = false
    }
    consumable212Jar {
        canBeConsumed = true
        canBeResolved = false
    }
}

artifacts {
    consumable211Jar(crossBuildScala_211Jar)
    consumable212Jar(crossBuildScala_212Jar)
}
```

_b/build.gradle:_

```
dependencies {
    crossBuildScala_211Implementation project(path: ':a', configuration: 'consumable211Jar')
    crossBuildScala_212Implementation project(path: ':a', configuration: 'consumable212Jar')
}
```

I could find anything about it in the plugin documentation. Any pointers would be highly-appreciated.

**Comment by prokod** [comment]
@bmuschko 
The plugin does not get rid of "default" version of scala lib - This is why also, the testing is chosen to be based on default scala version for reasons of simplicity and initial plugin robustness.
So when you define two crossbuild variants for one project you actually have three logical compilation variants: `crossbuild1`, `cerossbuild2` and `default`
The "bridge" so to speak between cross build enabled projects and non cross build enabled projects is the `default` variant
If you will set the `default` crossbuild to 2.12 in project `a` then you do not have any problem to consume project `a` from project `b` which is compiled for 2.12 only
It is mentioned in doc https://github.com/prokod/gradle-crossbuild-scala#cross-building---configuration-options. look for `default-variant`

**Comment by bmuschko** [comment]
> The plugin does not get rid of "default" version of scala lib - This is why also, the testing is chosen to be based on default scala version for reasons of simplicity and initial plugin robustness.

Got it. It is a little but confusing from the end user's perspective. Maybe just something that needs to be communicated clearly. Most end users simply call the `build` or `check` task and then potentially would expect multi-version compilation and packaging to happen.

> The "bridge" so to speak between cross build enabled projects and non cross build enabled projects is the default variant
If you will set the default crossbuild to 2.12 in project a then you do not have any problem to consume project a from project b which is compiled for 2.12 only

OK, I am not sure that it would cover all of the following use cases though:

1. `a` produces 2.11 and 2.12 variants, `b` consumes just `2.11` (not the default)
2. `a` produces 2.11 and 2.12 variants, `b` consumes just `2.12` (I believe this is what would happen if 2.12 is the default)
3. `a` produces 2.11 and 2.12 variants, `b` consumes `2.11` and `2.12` because it also produces `2.11` and `2.12` variants itself.

From the documentation, I still don't understand how you would do this without the code that I mentioned above. Can you give me a concrete code example that demonstrates the 3 use cases?

_Not really related to this issue but wanted to mention it in this context:_

Also wanted to mention that there's a general, potential issue with the replacement behavior for dependencies. While the variant is replaced at runtime for a dependency, you might want to use different version of a dependency per variant. For example, for Scala 2.11 you may want to use `org.scalatest:scalatest_2.11:3.1.2` but for Scala 2.12 you want to use `org.scalatest:scalatest_2.12:3.2.3`.

I think the better approach would be something similar to what Gradle core provides with [variant-aware dependency management](https://docs.gradle.org/current/userguide/variant_model.html). Maybe the plugin should actually use that concept instead as the underlying way to model variants. Not sure if it would be suitable for modeling the Maven GAVs for Scala dependencies though.

**Comment by prokod** [comment]
> Also wanted to mention that there's a general, potential issue with the replacement behavior for dependencies. While the variant is replaced at runtime for a dependency, you might want to use different version of a dependency per variant. For example, for Scala 2.11 you may want to use org.scalatest:scalatest_2.11:3.1.2 but for Scala 2.12 you want to use org.scalatest:scalatest_2.12:3.2.3.

This is supported through the generated crossbuild configurations the plugin provides the user with - you have actually used that in #102

> I think the better approach would be something similar to what Gradle core provides with variant-aware dependency management. Maybe the plugin should actually use that concept instead as the underlying way to model variants. Not sure if it would be suitable for modeling the Maven GAVs for Scala dependencies though.

The plugin leverages consume/producer internally. Leveraging this feature seems a good way to proceed forward regarding pom generation.

**Comment by bmuschko** [comment]
> This is supported through the generated crossbuild configurations the plugin provides the user with - you have actually used that in #102

Are you referring to `crossBuildScala_211RuntimeClasspath` and `crossBuildScala_212RuntimeClasspath`? Those configurations are not consumable and therefore cannot be used as a configuration assignment for a project dependency.

The error message:

```
> Could not resolve all task dependencies for configuration ':b:compileClasspath'.
   > Could not resolve project :a.
     Required by:
         project :b
      > Selected configuration 'crossBuildScala_211RuntimeClasspath' on 'project :a' but it can't be used as a project dependency because it isn't intended for consumption by other components.
```

For the following assignment

```
dependencies {
    implementation project(path: ':a:', configuration: 'crossBuildScala_211RuntimeClasspath')
}
```

Can you provide a complete example? A multi-project build where `a` produces 2.11 and 2.12, and `b` depends on `a` but also builds 2.11 and 2.12 variants.

**Comment by prokod** [comment]
> Are you referring to crossBuildScala_211RuntimeClasspath and crossBuildScala_212RuntimeClasspath? Those configurations are not consumable and therefore cannot be used as a configuration assignment for a project dependency.

No you are correct but you have crossBuildScala_211Compile, crossBuildScala_211Implementation ... which the plugin provides for you to use in dependencies block

Please have a look in the test cases you can "unflatten" one of the tests as a full fledge example.
I recommend first looking here https://github.com/prokod/gradle-crossbuild-scala/blob/7894e030bded69880ed9fb8ef520966a98d622c1/src/test/groovy/com/github/prokod/gradle/crossbuild/CrossBuildPluginCompileMultiModuleAdvancedTest.groovy#L2400 This is the latest real mini cross build example used for testing. You can unflatten it so to speak and make it into a stand alone project.

If you still feel this is not enough lmk please.

**Comment by bmuschko** [comment]
I had a look at the code of the test case and re-read the plugin documentation but I still don't understand the philosophy. I am surprised that other users of the plugin seem to "just get it".

Let me ask you the following questions:

1. To define project dependencies, you simply go with the `default` configuration e.g. `implementation project(':a')`? You do not need to spell out specific configurations.
2. When you run the `build` task, all combinations of variants will be exercised automatically and that is the case for project dependencies as well?
3. Explain again how publishing is even relevant to the test case? Does this only work correctly with publishing or not? Just wanted to state again that Gradle does not need to publish artifacts of a project dependencies. It simply refers to the compiled class files which is far more efficient than building & publishing a JAR just as a reference for a project dependency.

**Comment by prokod** [comment]
> To define project dependencies, you simply go with the default configuration e.g. implementation project(':a')? You do not need to spell out specific configurations.

The plugin is doing it behind the scene. There are, I can call them parallel dependency trees created for each variant based on the "default" so to speak blueprint.

> When you run the build task, all combinations of variants will be exercised automatically and that is the case for project dependencies as well?

When you run build only one variant will be compiled - the default. You should use the cross build tasks the plugin adds to the task list, to build one or more variants (stating the cross build tasks for each variant one after the other in the command line)

> Explain again how publishing is even relevant to the test case? Does this only work correctly with publishing or not? Just wanted to state again that Gradle does not need to publish artifacts of a project dependencies. It simply refers to the compiled class files which is far more efficient than building & publishing a JAR just as a reference for a project dependency.

Because publish task by default runs all publish tasks generated from the publish dsl you write in your build.gradle files, and because the plugin generated publish tasks if you use it, and because the plugin ties publish task via build jar task, then as a waterfall action once you run publish you actually build all variants.
You could achieve the same without publishing, with your own dedicated task that depends on all the cross build tasks (for all the different scala variants).
Then when calling it all the cross built artifacts will get generated.

A side note, are you experienced with gradle philosophy of task first? Have you worked with ant once or make ? they are closer in that sense  This is very different from the maven philosophy and needs adjusting to.

**Comment by bmuschko** [comment]
> Because publish task by default runs all publish tasks generated from the publish dsl you write in your build.gradle files, and because the plugin generated publish tasks if you use it, and because the plugin ties publish task via build jar task, then as a waterfall action once you run publish you actually build all variants.
You could achieve the same without publishing, with your own dedicated task that depends on all the cross build tasks (for all the different scala variants). Then when calling it all the cross built artifacts will get generated.

Thanks for confirming that I do need to publish the artifacts of variants if I wanted to use them as project dependencies. That's a behavior I don't want really want. It will likely be one of the reasons why I can't use your plugin for my project unfortunately.

The point I was trying to get at was the use case "no publishing involved". That's why I registered consumable artifacts in my sample project.

> A side note, are you experienced with gradle philosophy of task first? Have you worked with ant once or make ? they are closer in that sense This is very different from the maven philosophy and needs adjusting to.

I guess you mean `Task.doFirst` or Gradle tasks in general? Yeah, well experienced with Gradle with all major concepts. Plus I worked with Ant for over 5 years.

**Comment by prokod** [comment]
@bmuschko the plugin does not have publishing first in mind if you want to you can if you don't you just use the artifacts from the cross build task. I hope you will find the right tools for your project, and thanks for trying out the plugin :)

**Comment by prokod** [comment]
This is obsolete - I would consider this as signal to improve documentations in that regard. Any suggestion will be more then welcome!
