### ISSUE TITLE
Current maintenance and development effort of plugin

### ISSUE THREAD

**Issue by bmuschko** [prokod/gradle-crossbuild-scala#104]
I'd like to get a feeling for how active this project still is. I opened a couple of issues and would like to see them addressed. This could potentially mean that I'd submit a PR for one or all of the issues. Before I do so, I want to ensure the project is still actively maintained and will ship new releases.

Thanks for your feedback. I appreciate it and keep up the good work!

**Comment by prokod** [comment]
@bmuschko 
I appreciate the interest again, feel free to contribute :) I am still here

**Comment by bmuschko** [comment]
It's good to hear that we still have a maintainer. :-) Personally, I'd prefer if the owner(s) could take on the lead on some of the implementations but I do understand that time can be scarce. Of the issues I opened, are you planning to implement any of those soon? If you don't then I will probably have a look.

**Comment by prokod** [comment]
IMO some of the issues are from poor documentation probably :) As most of the things are built in already. I will close this and we can open specific issue against documentation.

**Comment by bmuschko** [comment]
Sounds good.
