### ISSUE TITLE
Question: How to pass on extra information to subprojects?

### ISSUE THREAD

**Issue by Jolanrensen** [prokod/gradle-crossbuild-scala#116]
I'm currently trying to apply this plugin to my Gradle project which should support a LOT of Spark versions and for some of those separate Scala versions. (Basically everything Apache has released for Spark 3.0.0+)
My setup in the parent project looks something like:
```kotlin
subprojects {
    apply(plugin = "com.github.prokod.gradle-crossbuild-scala")

    crossBuild {
        scalaVersionsCatalog = mapOf(
            "2.13" to "2.13.8",
            "2.12" to "2.12.15",
        )

        builds {
            for (spark in sparkVersionsForBoth)
                create(spark) {
                    scalaVersions = mutableSetOf("2.12", "2.13")
                }

            for (spark in sparkVersionsFor2_12)
                create(spark) {
                    scalaVersions = mutableSetOf("2.12")
                }
        }
    }
}
```
However, due to the complexity of the project, we cannot just swap out the scala/spark version and expect everything to work. There are some issues that can only be solved by replacing some pieces of code since some classes we use are only present from Spark 3.2+. To solve this, we use [JCP](https://github.com/raydac/java-comment-preprocessor). However, that plugin needs to pass on some variables like:
```kotlin
tasks.preprocess {
    ...
    vars.set("spark" to sparkVersion, "scala" to scalaVersion)
}
```
Now my question is, how can I pass on these versions based on which cross building variant is happening?

**Comment by prokod** [comment]
Hi @Jolanrensen I hope I understand you correctly, If so "injection" of different pieces of code per Scala version will be solved by #78. To handle also different spark versions , Its a question whether mapping code pieces to different Scala versions satisfies your project's needs. Otherwise we will need to come up with a more generic approach to code pieces mapping (not only Scala version based). It will help a lot if you could provide scaled down project (two subprojects is enough) for me to test this feature on. It should include small enough code change between the two subprojects that if not done correctly by the plugin the compilation fails.

**Comment by Jolanrensen** [comment]
@prokod I made a small sample project with a scala- and kotlin submodule, similar to my own project. https://github.com/Jolanrensen/gradle-crossbuild-sample
It aims to build the submodules for many scala/spark combinations using java-comment-processor to solve incompatibilities with the scala/spark library on older versions. 
IntelliJ doesn't always plays nice with jcp yet, despite my attempts, but I wrote some comments for how to handle those. If you're using another IDE you're probably fine.
Edit: jpc cooperation is better now

**Comment by prokod** [comment]
@Jolanrensen 
I think that keeping any custom plugins decoupled from each other is the main governing principal to adhere in this context. So keeping that in mind I think of the following strategy:
1. I am going to add to each cross compile variant a "landing" area where specific code for that variant should be.
2. Using JCP you can preprocess code and direct the output to that "landing" area.
3. Controlling build lifecycle should still be the same hopefully like in a simple non cross built scenario (as per JCP Gradle examples)


Regarding the other comments in your sample project. They are valid and should be put as issues on the issue board.

Thanks for the sample project!
Any feedback is welcomed
