### ISSUE TITLE
pom dependency scopes correct for main build but incorrect for crossbuilds

### ISSUE THREAD

**Issue by alexm-sky** [prokod/gradle-crossbuild-scala#128]
Hello, thank you for the plugin. It's worked well except for the issue below. 
Possibly related to https://github.com/prokod/gradle-crossbuild-scala/issues/111

Gradle 6.8.3
Plugin 0.14.1

**Issue**
Generated pom files for crossbuilds set all dependencies to `runtime` scope when some should be `compile` scope. The main build pom file has the correct scopes. In the `build.gradle` some dependencies are in `api` and some are in `implementation`.

**Expected**
The pom files generated for the cross-builds should match the `build.gradle` scopes and the main file.

I did read the instructions in the readme but I may have missed something if this is not a bug.

build.gradle extract
```
String scala2_13 = '2.13.10'
String scala2_12 = '2.12.17'

crossBuild {
    builds {
        scala {
            scalaVersions = [scala2_12, scala2_13]
        }
    }
}

dependencies {
    api(
            "my.company:some-kafka-lib:${versions.my_lib}"
    )

    implementation(
            "org.scala-lang:scala-library:${scala2_13}",
            "io.circe:circe-core_2.13:${versions.circe}"
    )
}

publishing {
    publications {
        mavenLib(MavenPublication) {
            from components.java
        }

        crossBuildScala_213(MavenPublication) {
            artifact crossBuildScala_213Jar
            artifact sourcesJar
        }

        crossBuildScala_212(MavenPublication) {
            artifact crossBuildScala_212Jar
            artifact sourcesJar
        }
    }
}
```
After running `./gradlew.bat :my-module:publishToMavenLocal` the following is the pom for the main build.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>my.company</groupId>
  <artifactId>my-lib</artifactId>
  <version>1.14.0</version>
  <dependencies>
    <dependency>
      <groupId>my.company</groupId>
      <artifactId>some-kafka-lib</artifactId>
      <version>1.47.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.scala-lang</groupId>
      <artifactId>scala-library</artifactId>
      <version>2.13.10</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>io.circe</groupId>
      <artifactId>circe-core_2.13</artifactId>
      <version>0.14.2</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</project>

```

The 2.12 and 2.13 builds have the same pom file EXCEPT the scope of `some-kafka-lib` is `runtime`. (and obviously also versions/names are different).

**Comment by prokod** [comment]
@alexm-sky thanks for raising the detailed issue. I will look at it soon . I was occupied with Scala 3 compilation, among other things
