### ISSUE TITLE
Support incremental build

### ISSUE THREAD

**Issue by tnielens** [prokod/gradle-crossbuild-scala#133]
It seems that the plugin doesn't support [incremental builds](https://docs.gradle.org/current/userguide/incremental_build.html). Running twice `./gradlew crossBuildAssemble` takes the same amount of time. In comparison, when running twice `./gradlew assemble`, the second run is much faster than the first one because gradle notices no work is needed.

Our usecase is a large multi-module published repo. With the gradle-crossbuild-scala plugin, losing the gradle incremental build and [build cache](https://docs.gradle.org/current/userguide/build_cache.html) is a performance regression. When the incremental build kicks in, running incrementally built tasks is fast. With the plugin, every crossBuild command does all the work again.

Tested plugin version 0.15.0.

**Comment by prokod** [comment]
Hi @tnielens Thank you for the feedback. I will take it as a feature and work on it after finalizing publishing overhaul for 0.16.0

**Comment by prokod** [comment]
Hello again @tnielens 

I was setting some test where I ran consecutively a build a project with multiple Scala variants and when observing the output from the second run, Gradle informed that relevant tasks are skipped:

```
> Task :app:compileCrossBuild330_212Scala UP-TO-DATE
[:app(task)] Excluding from compilation detected duplicate source file: [/tmp/spock__gradle_7.6.2_defau_0_dir5525863609523393800/app/src/main/scala/com/github/prokod/it/gradleCrossbuildSample/Main.scala]
Caching disabled for task ':app:compileCrossBuild330_212Scala' because:
  Build cache is disabled
Skipping task ':app:compileCrossBuild330_212Scala' as it is up-to-date.
Resolve mutations for :app:processCrossBuild330_212Resources (Thread[Execution worker Thread 7,5,main]) started.
:app:processCrossBuild330_212Resources (Thread[Execution worker Thread 7,5,main]) started.

...

BUILD SUCCESSFUL in 1m 45s
7 actionable tasks: 2 executed, 5 up-to-date
``` 

I would appreciate if you could give some more details, as my test is very basic :
- Which tasks are not skipped even though they should - If you can paste logs of the original build and the consecutive build it will greatly help.
- If possible, some stripped down example build where you observe certain tasks being executed even though no changes to code happened between runs.

**Comment by tnielens** [comment]
Hi @prokod,

I've been trying on my side as well with a small dummy project, and indeed cannot reproduce the issue I reported above. The cache and incremental building works fine. I'll give a look at a bigger library project of ours in which I do reproduce the issue and try to figure out what is going wrong with our usage of your plugin. I'll let you know should there be any interesting findings.

Thanks for looking into this issue.

**Comment by prokod** [comment]
Please do re-open if need be
