### ISSUE TITLE
[Need help] Adding Scala 3 support to an existing Scala 2.xx gradle build

### ISSUE THREAD

**Issue by jtduffy** [prokod/gradle-crossbuild-scala#139]
Hello - I hope this isn't too naive of a question, but I'm fairly new to the Scala ecosystem, and inherited a task to update an existing cross build gradle build to pubish a Scala 3 version.

The target module is [here](https://github.com/newrelic/newrelic-java-agent/tree/scala3-cross-build/newrelic-scala-api) (part of the New Relic Java Agent) and this is [my attempt](https://github.com/newrelic/newrelic-java-agent/blob/scala3-cross-build/newrelic-scala-api/build.gradle.kts) to add a Scala 3 build to the existing `build.gradle.kts`. For reference, this is the [original gradle file](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-scala-api/build.gradle.kts).

With these changes, when I execute the `publishToMavenLocal` task, I get the following error and no artifact is generated. (I snipped the stack trace; I can provide the full stack if necessary)
```
> Task :newrelic-scala-api:compileCrossBuildScala_3Scala
[Warn] : bad option '-target:8' was ignored
java.lang.ClassCastException: dotty.tools.dotc.core.Symbols$NoSymbol$ cannot be cast to dotty.tools.dotc.core.Symbols$ClassSymbol while typechecking /Users/jduffy/dev/newrelic-java-agent/newrelic-scala-api/src/main/scala/com/newrelic/scala/api/TraceOps.scala
## Exception when compiling 1 sources to /Users/jduffy/dev/newrelic-java-agent/newrelic-scala-api/build/classes/scala/crossBuildScala_3
java.lang.ClassCastException: dotty.tools.dotc.core.Symbols$NoSymbol$ cannot be cast to dotty.tools.dotc.core.Symbols$ClassSymbol
dotty.tools.dotc.core.Symbols$Symbol.asClass(Symbols.scala:178)
dotty.tools.dotc.core.Definitions.UnitClass(Definitions.scala:563)
dotty.tools.dotc.typer.ProtoTypes$SelectionProto.qualifies$1(ProtoTypes.scala:210)
dotty.tools.dotc.typer.ProtoTypes$SelectionProto.liftedTree1$1(ProtoTypes.scala:215)
dotty.tools.dotc.typer.ProtoTypes$SelectionProto.isMatchedBy(ProtoTypes.scala:228)
```

Any help or advice is appreciated. If you need more info, let me know.  Thank you!

**Comment by prokod** [comment]
@jtduffy Can you please change the Scala 3 compiler version to 3.2.1 instead of 3.3.1 where scalaVersionsCatalog  is set and see if the error goes away?

Another test, leaving things as they are and adding in the builds block `targetCompatibility.strategy` setting it to `smart`. Does the error goes away and artifact created?

**Comment by jtduffy** [comment]
@prokod  Thanks so much for the quick response. I tried the following:
- Changing the  `scalaVersionsCatalog` for version 3 to `"3" to "3.2.1"` 
- Changing the `targetCompatibility.strategy` to `smart`
- Changing both the `scalaVersionCatalog` and setting the `targetCompatibility.strategy`

Each resulting in the same exception being thrown.

I do have a backup plan, which is to simply create a new subproject specifically for building the API with Scala3 and publishing it outside the current API project.
