### ISSUE TITLE
publishing source & javadoc jars for all scala versions

### ISSUE THREAD

**Issue by atais** [prokod/gradle-crossbuild-scala#147]
Hello.

I know it's a known limitation, but currently its blocking https://github.com/allure-framework/allure-java/pull/1106

> Please, make sure the scala doc and the sources are published as well (as per Maven Central requirement)

Is there any way to get around it?

**Comment by atais** [comment]
Uh oh, I think its possible, please see:

https://github.com/allure-framework/allure-java/pull/1107

maybe you can just add it to the docs :)

**Comment by prokod** [comment]
Hi there,

Nice one :D The documentation on that front was not updated after I
introduced  an overhauled  publishing approach using components.
I believe though it is the exact same scaladoc artifact from the "default"
Scala version (when running default build task), Regarding the source jar I
believe you do it correctly and I will add it to documentation
For simple projects where scaladoc is not changing with Scala version this
is a valid solution imo

Many thanks for the contribution!

**Comment by prokod** [comment]
@atais please see the following example which uses the plugin extra properties also

```kotlin
    crossBuild {
        scalaVersionsCatalog = mapOf(
            "2.12" to "2.12.19",
            "2.13" to "2.13.14"
        )
        builds {
            register("scala") {
                scalaVersions = setOf("2.12", "2.13")
            }
        }
    }

    // Create Jar type task for custom sources/scaladoc artifacts
    sourceSets.filter { it.name.startsWith("crossBuild") }.forEach { sourceSet ->
        // Makes the sourceSet scalaCompilerVersion extra property available to configure the following tasks
        val scalaCompilerVersion : String by sourceSet.extra
        val scalaVersion = scalaCompilerVersion.substring(0, scalaCompilerVersion.lastIndexOf('.'))

        tasks.register<Jar>("${sourceSet.name}SourcesJar") {
            from(sourceSet.allSource)
            archiveBaseName.set("${archiveBaseName.get()}_${scalaVersion}")
            archiveClassifier.set("sources")
        }

        tasks.register<Jar>("${sourceSet.name}ScaladocJar") {
            from(tasks.scaladoc)
            archiveBaseName.set("${archiveBaseName.get()}_${scalaVersion}")
            archiveClassifier.set("scaladoc")
        }
    }

    // Publish with both source and scaladoc
    publishing {
        publications {
            create<MavenPublication>("crossBuildScala_212") {
                from(components["crossBuildScala_212"])
                artifact(tasks["crossBuildScala_212SourcesJar"])
                artifact(tasks["crossBuildScala_212ScaladocJar"])
            }
            create<MavenPublication>("crossBuildScala_213") {
                from(components["crossBuildScala_213"])
                artifact(tasks["crossBuildScala_213SourcesJar"])
                artifact(tasks["crossBuildScala_213ScaladocJar"])
            }
        }
    }
```

**Comment by atais** [comment]
Thanks for the support.

I think it's mainly @baev who can directly benefit it :) but I can't tag him here. 

I see you've also participated in the discussion on allure repo so if there is anything else there that should've been done please inform @baev directly.

Thanks a lot!
