### ISSUE TITLE
Support java-library configurations

### ISSUE THREAD

**Issue by netvl** [prokod/gradle-crossbuild-scala#63]
The old `compile` and `runtime` configurations are obsolete, and are planned to be removed in Gradle 7.0: https://github.com/gradle/gradle/issues/8585#issuecomment-480288521

While 7.0 is still a bit far from being released, the effects of the deprecation are already there. In particular, the `implementation` configuration generates dependencies in POM with the `runtime` scope, and the proper way to avoid it is to use the `api` configuration.

I see in the docs that the `api` configuration is not supported, but are there plans to add support for it eventually?

**Comment by prokod** [comment]
Hi,

I am not sure I follow you on that one. `api` is not used as means to influence the scope on pom file. It is there to help library developers to declare that those dependencies that are marked as `api` should be transitively added to classpath through all the dependency tree consuming the relevant developed lib as the user interface of that lib uses types from that `api` marked dependency/ies.
I hope this is clear enough.

If you can clarify what exactly you are trying to achieve (maybe adding some sample project) I can maybe try and give you better guidance.

Any how in general I do plan to add this. Even sooner then later if it will get up voted :)

Cheers

**Comment by Arthurm1** [comment]
Hi

Is it still on the cards to add this?  It would be handy if it was :smiley:

Currently if you use **implementation** to declare the Scala library dependency...
```
dependencies {
    implementation ("org.scala-lang:scala-library:2.13.3")
}
```
Gradle gives an error on compile because it can't find the scala-library version...
```
A problem occurred configuring project ':Foo'.
> assert possibleDefaultScalaVersions.size() > 0
         |                            |      |
         []                           0      false

  Could not discover default scala version. Scala library dependency is missing ?
```
It works fine if the Scala library is declared using **compile**...
```
dependencies {
    compile ("org.scala-lang:scala-library:2.13.3")
}
```


Also, for the dependencies that include `?` Gradle can't resolve `api` dependencies...
```
  ./gradlew clean Foo:dependencies
```
gives...
```
compileClasspath - Compile classpath for source set 'main'.
+--- com.typesafe.scala-logging:scala-logging_?:3.9.2 FAILED
```
when the dependency is declared with `api` like...
```
api("com.typesafe.scala-logging:scala-logging_?:3.9.2")
```
but works when the dependency is declared using `compile`...
```
compile("com.typesafe.scala-logging:scala-logging_?:3.9.2")
```
then no error...
```
compileClasspath - Compile classpath for source set 'main'.
\--- com.typesafe.scala-logging:scala-logging_2.13:3.9.2
```

**Comment by prokod** [comment]
Hi @Arthurm1 :)
I would like first to point out that from version 0.12 onwards you do not need use ? for scala 3rd party libs. You can choose one scala version which is naturally the default scala version of your project and the replacement of the scala version while you cross building is done anyhow.

I will try and clear some time to evaluate the work needed. Keep tuned ;)

**Comment by loicdescotte** [comment]
Hi,

> api [...] is there to help library developers to declare that those dependencies that are marked as api should be transitively added to classpath through all the dependency tree

I think that is something very useful for lib developpers, as it avoids lib users to add all the transitive dependencies (and to know what lib they need to add). 

It would be great to have this feature compatibility for cross building scala libs :)

**Comment by prokod** [comment]
Reclosing after adding correct fix milestone
