### ISSUE TITLE
cross-compile imports

### ISSUE THREAD

**Issue by frankivo** [prokod/gradle-crossbuild-scala#70]
My code depends on "import scala.jdk.CollectionConverters._" in Scala 2.13 which is predecesed by "import collection.CollectionConverters._" in Scala 2.11.

Any hints on how, if at all possible, I could resolve that?

**Comment by prokod** [comment]
Hi frankivo,
This is an interesting use case. What about adding a module that will contain all code from scala 2.11 ? The plugin supports that to some extent. This approach is also supported in relevant discussion [here](https://github.com/scala/scala-dev/issues/640). I am aware that this approach duplicates code but I do not see right now a lot of other more appealing approaches.

**Comment by frankivo** [comment]
That could work I guess. Though the code is exactly the same apart from the import.

**Comment by frankivo** [comment]
Maybe I'll just write something myself do the asScala part.
