### ISSUE TITLE
Feature request: source folder per scala version.

### ISSUE THREAD

**Issue by borissmidt** [prokod/gradle-crossbuild-scala#78]
Hey prokod,

I was thinking about the sbt feature where you can have a specific source folder per scala version to override some classes. This would make it easier to specialize libraries that span from 2.11 to 2.13. 

i.e. if you have some library that exists for 2.11 and 2.12 and it broke its api when it switched to 2.12 to 2.13. Then you either have to drop 2.11 of stay at the older library version. But if you can override the classes to be different depending on the version then you can just resolve this issue. 

Do you think this feature would be hard to implement? Would it be a welcoming PR?

Kind regards, Boris Smidt

**Comment by prokod** [comment]
Hi @borissmidt,

This is a good idea.
By overriding you actually mean that we will support `src/../scala-2.11` `src/../scala-2.12` etc. dirs by default for each source set ? If so this seems straight forward:

- A quick impl. should be easy to achieve in case the mutual exclusive of classes is kept across the different src scala dirs (incl. default one)
- More thought should be given if we want to achieve an override effect where the default `src/.../scala` dir should have the least priority.

lmk how you would like to go forward with this further,

Noam

**Comment by borissmidt** [comment]
I can take a look at the current code and see how the sourcesets are done
and try to implement something with that.

I'll see when i have time to do that. Hopefully tomorrow. I'll lookup the
behavior of sbt first.

**Comment by jvican** [comment]
@prokod @borissmidt Have you thought this through more? We're thinking of adopting this plugin and this feature would be fundamental for us to consider using it, as without it we won't be able to properly cross-compile.

**Comment by borissmidt** [comment]
We haven't really had the time to implement this. I actually think that
gradle is a second class citizen in scala. Atleast untill gradle has native
cross-building support.

**Comment by prokod** [comment]
Hi @jvican albeit what @borissmidt had written, as this is true it doesn't mean there is no place for Gradle to try scala cross compiling heads in :) I had put some effort to remove in latest build internal plugin technical debts and make it work with latest Gradle versions. I believe it is much more streamlined now and can handle new features. I can give it a go. I was thinking to tackle this feature in the next release. Follow us here for further developments. Thx for the interest.

Btw, currently I will try and follow sbt convention for that.

**Comment by jvican** [comment]
Excellent, happy to hear you're working on that @prokod Will follow this thread with interest, hopefully we'll be able to integrate with this plugin soon internally.
