### ISSUE TITLE
CompileOnly not picked up to multiple scala versions.

### ISSUE THREAD

**Issue by borissmidt** [prokod/gradle-crossbuild-scala#97]
Because i have a weird way of dooing gradle builds and i apply the scala-crossbuild plugin in an afterEvaluate setting. 

It seems that at that point it doens't pick up the compileOnly dependenceis for multiples scala versiosn.
So i have to state the compileOnly for each version for it to work.
```
dependecnies{
        compileOnly  project(":common")
        crossBuildV211CompileOnly project(":common")
        crossBuildV212CompileOnly project(":common")
}
```

**Comment by prokod** [comment]
@borissmidt sorry for the delayed reply. Can you share the build.gradle block where you apply the plugin in `afterEvaluate` ?

**Comment by borissmidt** [comment]
So it happens if i apply the plugin in an after evaluate block. After i have defined my dependencies. So it already applied the compile only dependency but then the crossbuild plugin doesn't pick it up i will see if i have the time to make a sample project.

**Comment by prokod** [comment]
Seems to me obsolete, if needed please do reopen / reiterate.
